<a href="https://colab.research.google.com/github/arvindbishnoii/arvindbishnoii/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# installing devito and importing modules 
#!pip install devito
#!pip install sympy
#!pip install numpy
#!pip install matplotlib
#!pip install pandas
import numpy as np
import sympy as sp
import pandas as pd
from sympy import *
from devito import *
from numpy import *


#A=100
#alpha = symbols(u'α')           # birth rate
#beta_e = symbols(u'β_e')        # the asymptomatic contact rate
#beta_i = symbols(u'β_i')        # is the symptomatic contact rate
#theta= symbols (u'θ')
#phi_e = symbols (u'Φ_e')       #  is the asymptomatic recovery rate
#phi_r = symbols (u'Φ_r')       # is the infected recovery rate
#phi_d = symbols (u'Φ_d')       # is the infected mortality rate
#sigma = symbols (u'σ')       # the inverse of the incubation period
#mu = symbols (u'μ')          # is the general (non-COVID-19) mortality rate

# declaring diffusion paramters as 1 for trial

#V_s = symbols (u'V_s')
#V_e = symbols (u'V_e')
#V_i = symbols (u'V_i')
#V_r = symbols (u'V_r')

# lets taks Alee coefficient as 1 for trial

#A = symbols (u'A')



# creating a grid
grid = Grid(shape=(100,100), extent=(1,1))
grid
#grid1=Grid(shape(50), extent=(1))



# for creating time function

#susceptible (S), exposed (E), infected (I), Recovered (R) and Dead (D). 
#The system of equations in the SEIRD model is given by:
S = TimeFunction(name='S', grid=grid,space_order=1,time_order=1)

E = TimeFunction(name='E', grid=grid,space_order=1,time_order=1)

I = TimeFunction(name='I', grid=grid,space_order=1,time_order=1)

R = TimeFunction(name='R', grid=grid,space_order=1,time_order=1)

D = TimeFunction(name='D', grid=grid,space_order=1,time_order=1)

alpha=TimeFunction(name='alpha', grid=grid,time_order=1)
beta=TimeFunction(name='beta', grid=grid,time_order=1)
Rep_num=TimeFunction(name='Rep_num', grid=grid,time_order=1)

#g.shape

N = S + E + I + R + D
N = TimeFunction(name='N', grid=grid,space_order=1,time_order=1)
# where N is the total population, i.e. N = S + E + I + R + D at each time t

In [23]:
#Eq1=Eq(S.dt, - (beta)/N * S* I)
#Eq1
#After giving some values to d,n,s,i

Eq1=Eq(S.dt, - (10)/50 * 20* 10)
Eq1                                                                                #1

Eq(Derivative(S(t, x, y), t), -40.0000000000000)

In [21]:
#Eq2=Eq(E.dt,  (beta)/N * S* I - alpha * E)
#Eq2   


Eq2=Eq(E.dt,  (10)/50 * 20* 10 - 15 * 10)
Eq2                                                                               #1

Eq(Derivative(E(t, x, y), t), -110.000000000000)

In [22]:
eq2_stencil = solve(Eq2, E.forward)
update_eq2 = Eq(E.forward, eq2_stencil)
update_eq2

Eq(E(t + dt, x, y), dt*(-110.0 + E(t, x, y)/dt))

In [55]:
op = Operator([update_eq2]  + [update] + [Eq(I.forward,solve(Eq3, I.forward))] + [Eq(R.forward,solve(Eq4, R.forward))] +  [Eq(D.forward,solve(Eq5, D.forward))] )
op

Cpu64AdvCOperator[Kernel]<int; struct dataobj *,struct dataobj *,struct dataobj *,struct dataobj *,struct dataobj *,const float,const int,const int,const int,const int,const int,const int,struct profiler *>

In [56]:
op(time=4, dt=dt)

Operator `Kernel` ran in 0.01 s
INFO:Devito:Operator `Kernel` ran in 0.01 s

PerformanceSummary([(PerfKey(name='section0', rank=None),
                     PerfEntry(time=0.000301, gflopss=0.0, gpointss=0.0, oi=0.0, ops=0, itershapes=[]))])

In [47]:
S.data[4]

Data([[-480., -480., -480., ..., -480., -480., -480.],
      [-480., -480., -480., ..., -480., -480., -480.],
      [-480., -480., -480., ..., -480., -480., -480.],
      ...,
      [-480., -480., -480., ..., -480., -480., -480.],
      [-480., -480., -480., ..., -480., -480., -480.],
      [-480., -480., -480., ..., -480., -480., -480.]], dtype=float32)

In [48]:
E.data[4]

Data([[-1320., -1320., -1320., ..., -1320., -1320., -1320.],
      [-1320., -1320., -1320., ..., -1320., -1320., -1320.],
      [-1320., -1320., -1320., ..., -1320., -1320., -1320.],
      ...,
      [-1320., -1320., -1320., ..., -1320., -1320., -1320.],
      [-1320., -1320., -1320., ..., -1320., -1320., -1320.],
      [-1320., -1320., -1320., ..., -1320., -1320., -1320.]],
     dtype=float32)

In [49]:
I.data[4]

Data([[1192., 1192., 1192., ..., 1192., 1192., 1192.],
      [1192., 1192., 1192., ..., 1192., 1192., 1192.],
      [1192., 1192., 1192., ..., 1192., 1192., 1192.],
      ...,
      [1192., 1192., 1192., ..., 1192., 1192., 1192.],
      [1192., 1192., 1192., ..., 1192., 1192., 1192.],
      [1192., 1192., 1192., ..., 1192., 1192., 1192.]], dtype=float32)

In [53]:
R.data[4]

Data([[-152., -152., -152., ..., -152., -152., -152.],
      [-152., -152., -152., ..., -152., -152., -152.],
      [-152., -152., -152., ..., -152., -152., -152.],
      ...,
      [-152., -152., -152., ..., -152., -152., -152.],
      [-152., -152., -152., ..., -152., -152., -152.],
      [-152., -152., -152., ..., -152., -152., -152.]], dtype=float32)

In [57]:
D.data[4]

Data([[160., 160., 160., ..., 160., 160., 160.],
      [160., 160., 160., ..., 160., 160., 160.],
      [160., 160., 160., ..., 160., 160., 160.],
      ...,
      [160., 160., 160., ..., 160., 160., 160.],
      [160., 160., 160., ..., 160., 160., 160.],
      [160., 160., 160., ..., 160., 160., 160.]], dtype=float32)

In [43]:
#TI is the average infectious period

T_i=10
#Eq3=Eq(I.dt,  alpha * E - I / T_i)
#Eq3  

Eq3=Eq(I.dt,  15 * 20 - 20 / T_i)
Eq3                                                                                  #1

Eq(Derivative(I(t, x, y), t), 298.000000000000)

In [50]:
#f is the fraction of all the removed individuals who die

f=20

#Eq4=Eq(R.dt,  (1 - f) / T_i * I)
#Eq4        

Eq4=Eq(R.dt,  (1 - f) / T_i * 20)
Eq4                                                                                                  #1

Eq(Derivative(R(t, x, y), t), -38.0000000000000)

In [54]:
#Eq5=Eq(D.dt,  (f) / T_i * I)
#Eq5 

Eq5=Eq(D.dt,  (f) / T_i * 20)
Eq5                                                                                                                                                                                         #1

Eq(Derivative(D(t, x, y), t), 40.0000000000000)

The system (1) is solved by starting from an initial time t = t0 where the values of the populations S(t0), E(t0), I(t0), R(t0), D(t0) are assigned on the basis of the available data and integrated up to a final time T.

In [31]:
from examples.seismic import TimeAxis

t0 = 0.  # Simulation starts a t=0
tn = 1000.  # Simulation last 1 second (1000 ms)
dt = 1.           # Time step from model grid spacing

time_range = TimeAxis(start=t0, stop=tn, step=dt)

In [25]:
stencil = solve(Eq1, S.forward)
update = Eq(S.forward, stencil)
update

Eq(S(t + dt, x, y), dt*(-40.0 + S(t, x, y)/dt))

In [ ]:
stencil

dt*(63*E(t, x, y) - 9.4 + I(t, x, y)/dt)

In [ ]:
op = Operator(update, opt="noop")
op

Cpu64NoopCOperator[Kernel]<int; struct dataobj *,struct dataobj *,const float,const int,const int,const int,const int,const int,const int,struct profiler *>

In [ ]:
op(time=1, dt=dt)

Operator `Kernel` ran in 0.01 s
INFO:Devito:Operator `Kernel` ran in 0.01 s

PerformanceSummary([(PerfKey(name='section0', rank=None),
                     PerfEntry(time=2.3e-05, gflopss=0.0, gpointss=0.0, oi=0.0, ops=0, itershapes=[]))])

In [ ]:
I.data[0]

#value of s after 20 timestamps

Data([[-2036.8011, -2036.8011, -2036.8011, ..., -2036.8011, -2036.8011,
       -2036.8011],
      [-2036.8011, -2036.8011, -2036.8011, ..., -2036.8011, -2036.8011,
       -2036.8011],
      [-2036.8011, -2036.8011, -2036.8011, ..., -2036.8011, -2036.8011,
       -2036.8011],
      ...,
      [-2036.8011, -2036.8011, -2036.8011, ..., -2036.8011, -2036.8011,
       -2036.8011],
      [-2036.8011, -2036.8011, -2036.8011, ..., -2036.8011, -2036.8011,
       -2036.8011],
      [-2036.8011, -2036.8011, -2036.8011, ..., -2036.8011, -2036.8011,
       -2036.8011]], dtype=float32)

In [ ]:
print(op.ccode)

#define _POSIX_C_SOURCE 200809L
#define START_TIMER(S) struct timeval start_ ## S , end_ ## S ; gettimeofday(&start_ ## S , NULL);
#define STOP_TIMER(S,T) gettimeofday(&end_ ## S, NULL); T->S += (double)(end_ ## S .tv_sec-start_ ## S.tv_sec)+(double)(end_ ## S .tv_usec-start_ ## S .tv_usec)/1000000;

#include "stdlib.h"
#include "math.h"
#include "sys/time.h"

struct dataobj
{
  void *restrict data;
  int * size;
  int * npsize;
  int * dsize;
  int * hsize;
  int * hofs;
  int * oofs;
} ;

struct profiler
{
  double section0;
} ;


int Kernel(struct dataobj *restrict S_vec, const float dt, const int time_M, const int time_m, const int x_M, const int x_m, const int y_M, const int y_m, struct profiler * timers)
{
  float (*restrict S)[S_vec->size[1]][S_vec->size[2]] __attribute__ ((aligned (64))) = (float (*)[S_vec->size[1]][S_vec->size[2]]) S_vec->data;

  for (int time = time_m, t0 = (time)%(2), t1 = (time + 1)%(2); time <= time_M; time += 1, t0 = (time)%(2), t1 = (time + 1)%(2))
  {
    /* Begin section0 */
    START_TIMER(section0)
    for (int x = x_m; x <= x_M; x += 1)
    {
      for (int y = y_m; y <= y_M; y += 1)
      {
        S[t1][x + 1][y + 1] = dt*(-4.0e+1F + S[t0][x + 1][y + 1]/dt);
      }
    }
    STOP_TIMER(section0,timers)
    /* End section0 */
  }

  return 0;
}

Model parameters estimation-

In [ ]:
# vector stack

a = np.array([[1], [2], [3]])
f = np.array([[1], [2], [3]])
rho = np.array([[1], [2], [3]])

stacked_vectors=np.vstack((a,f,rho))
stacked_vectors

i = np.array([[320], [396], [472]])
r = np.array([[24], [24], [32]])
d = np.array([[13], [16], [19]])

stacked_vectors1=np.vstack((i,r,d))
stacked_vectors1

array([[320],
       [396],
       [472],
       [ 24],
       [ 24],
       [ 32],
       [ 13],
       [ 16],
       [ 19]])

In [ ]:
a = np.array([1, 2, 3])
f = np.array([1, 2, 3])
rho = np.array([1, 2,3])

stacked_vectors=np.vstack((a,f,rho))
stacked_vectors

i = np.array([320, 396, 472])
r = np.array([24, 24, 32])
d = np.array([13, 16, 19])

stacked_vectors1=np.vstack((i,r,d))
stacked_vectors1

array([[320, 396, 472],
       [ 24,  24,  32],
       [ 13,  16,  19]])

In [ ]:
#perimeter estimation a,f,rho
'''
def u(v):
  a = np.array([1,2, 3])
  f = np.array([1, 2, 3])
  rho = np.array([1, 2, 3])
  v=np.vstack((a,f,rho))
  return v
'''
def fun_rosenbrock(x):
  return x * 63 - 6.3 

#return np.array([10 * (x[1] - x[0]**2), (1 - x[0]) , (3 - x[2])])

from scipy.optimize import least_squares,leastsq
y=np.array([94])
i = np.array([320, 396, 472])
r = np.array([24, 24, 32])
d = np.array([13, 16, 19])
n = np.array([i[0],r[0],d[0]])
Y=np.vstack((i,r,d))

res_1 = leastsq(fun_rosenbrock, y[0])
res_1

(array([0.1]), 2)

In [ ]:
from scipy.optimize import leastsq
def func(x):
    return 2*(x-3)**2+1
leastsq(func, 0)

(array([2.99999999]), 1)

In [ ]:
import numpy as np
from numpy import exp
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.special import factorial
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import statsmodels.api as sm
from statsmodels.api import Poisson
from scipy import stats
from scipy.stats import norm
from statsmodels.iolib.summary2 import summary_col

i = np.array([320, 396, 472])
r = np.array([24, 24, 32])
d = np.array([13, 16, 19])
 # x = np.array([320, 32, 19])
X=np.vstack((i[0],r[0],d[0]))

y = np.array([1, 2, 3])

stats_poisson = Poisson(y, X).fit()
print(stats_poisson.summary())

Optimization terminated successfully.
         Current function value: 1.824455
         Iterations 4
                          Poisson Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                    3
Model:                        Poisson   Df Residuals:                        2
Method:                           MLE   Df Model:                            0
Date:                Sat, 23 Jul 2022   Pseudo R-squ.:                 -0.2652
Time:                        22:07:12   Log-Likelihood:                -5.4734
converged:                       True   LL-Null:                       -4.3260
Covariance Type:            nonrobust   LLR p-value:                       nan
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0005      0.003      0.156      0.876      -0.005       0.006
==============================================================================

In [ ]:
shape=(10,10)
be=np.empty(shape=shape )

# We can now write the PDE
S.dt =  -beta * 20 * 60 / 100
S.dt

-12*beta(time, x, y)

In [ ]:
df1=pd.read_csv('/content/dpc-covid19-ita-regioni new.csv')  
df1.head(50)

,data,stato,region_code,region,lat,long,hospitalized with symptoms,intensive care,total hospitalized,home isolation,...,note,intensive care entrances,note_test,note_cases,total_positives_molecular_test,total positive rapid antigen test,molecular test swabs,rapid antigen test swabs,codice_nuts_1,codice_nuts_2
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2020-02-24T18:00:00,ITA,6,Friuli Venezia Giulia,45.649435,13.768136,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2020-02-24T18:00:00,ITA,12,Lazio,41.892770,12.483667,1,1,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2020-02-24T18:00:00,ITA,7,Liguria,44.411493,8.932699,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2020-02-24T18:00:00,ITA,3,Lombardia,45.466794,9.190347,76,19,95,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2020-02-24T18:00:00,ITA,11,Marche,43.616760,13.518875,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2020-02-24T18:00:00,ITA,14,Molise,41.557748,14.659161,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2020-02-24T18:00:00,ITA,21,P.A. Bolzano,46.499335,11.356624,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2020-02-24T18:00:00,ITA,22,P.A. Trento,46.068935,11.121231,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2020-02-24T18:00:00,ITA,1,Piemonte,45.073274,7.680687,2,0,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2020-02-24T18:00:00,ITA,16,Puglia,41.125596,16.867367,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2020-02-24T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2020-02-24T18:00:00,ITA,19,Sicilia,38.115697,13.362357,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2020-02-24T18:00:00,ITA,9,Toscana,43.769231,11.255889,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2020-02-24T18:00:00,ITA,10,Umbria,43.106758,12.388247,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2020-02-24T18:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2020-02-24T18:00:00,ITA,5,Veneto,45.434905,12.338452,12,4,16,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2020-02-25T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2020-02-25T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2020-02-25T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2020-02-25T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2020-02-25T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,15,2,17,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2020-02-25T18:00:00,ITA,6,Friuli Venezia Giulia,45.649435,13.768136,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2020-02-25T18:00:00,ITA,12,Lazio,41.892770,12.483667,1,1,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2020-02-25T18:00:00,ITA,7,Liguria,44.411493,8.932699,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2020-02-25T18:00:00,ITA,3,Lombardia,45.466794,9.190347,79,25,104,127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2020-02-25T18:00:00,ITA,11,Marche,43.616760,13.518875,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2020-02-25T18:00:00,ITA,14,Molise,41.557748,14.659161,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2020-02-25T18:00:00,ITA,21,P.A. Bolzano,46.499335,11.356624,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2020-02-25T18:00:00,ITA,22,P.A. Trento,46.068935,11.121231,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2020-02-25T18:00:00,ITA,1,Piemonte,45.073274,7.680687,2,0,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2020-02-25T18:00:00,ITA,16,Puglia,41.125596,16.867367,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2020-02-25T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2020-02-25T18:00:00,ITA,19,Sicilia,38.115697,13.362357,1,0,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2020-02-25T18:00:00,ITA,9,Toscana,43.769231,11.255889,2,0,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2020-02-25T18:00:00,ITA,10,Umbria,43.106758,12.388247,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2020-02-25T18:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2020-02-25T18:00:00,ITA,5,Veneto,45.434905,12.338452,12,7,19,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2020-02-26T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2020-02-26T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2020-02-26T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2020-02-26T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2020-02-26T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,20,3,23,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2020-02-26T18:00:00,ITA,6,Friuli Venezia Giulia,45.649435,13.768136,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2020-02-26T18:00:00,ITA,12,Lazio,41.892770,12.483667,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2020-02-26T18:00:00,ITA,7,Liguria,44.411493,8.932699,6,0,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import numpy as np
from numpy import linalg as LA

# Our data
A = np.array([[1, 4, 16], [1, 0, 0], [1, 1, 1]])

y = np.array([[5], [1], [3]])

theta = LA.lstsq(A, y)

print(theta)

NameError: ignored

In [ ]:
from sklearn.metrics import mean_squared_error

y_actual = [11,27,41]

y_predicted = [69,102,136]

rms = mean_squared_error(y_actual, y_predicted, squared=False)
rms

NameError: ignored

In [ ]:
def equations(x):
  return x * 63 - 9.4

In [ ]:
0.14920635

In [ ]:
#Eq1=Eq(S.dt, - (D)/N * S* I)
#Eq1
#After giving some values to d,n,s,i

Eq1=Eq(I.dt, E * 63 - 9.4)
Eq1

Eq(Derivative(I(t, x, y), t), 63*E(t, x, y) - 9.4)